FROM node:22-alpine AS build
ARG VITE_AUTH_URL
ARG VITE_API_URL
ARG VITE_WS_URL
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
